//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Transactions = new HashSet<Transaction>();
            this.Settlements = new HashSet<Settlement>();
        }
    
        public int id { get; set; }
        public string Itemname { get; set; }
        public int Category_Id { get; set; }
        public string Unit { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settlement> Settlements { get; set; }
        public virtual Category Category { get; set; }

        public override string ToString()
        {
            return $"ID: {id}, Item Name: {Itemname}, Category ID: {Category_Id}, Unit: {Unit}, Location: {Location}, Description: {Description}";
        }

    }
}
