//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int id { get; set; }
        public int Item_Id { get; set; }
        public int Quantity { get; set; }
        public decimal Total { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public int User_Id { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
