-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 12:25:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema warehouseManagement
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `warehouseManagement` ;

-- -----------------------------------------------------
-- Schema warehouseManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `warehouseManagement` DEFAULT CHARACTER SET utf8 ;
USE `warehouseManagement` ;

-- -----------------------------------------------------
-- Table `warehouseManagement`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouseManagement`.`Users` ;

CREATE TABLE IF NOT EXISTS `warehouseManagement`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Role` ENUM('ADMIN', 'USER') NOT NULL,
  `Password` VARCHAR(64) NOT NULL,
  `Email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouseManagement`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouseManagement`.`Categories` ;

CREATE TABLE IF NOT EXISTS `warehouseManagement`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Category` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Category_UNIQUE` (`Category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouseManagement`.`Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouseManagement`.`Items` ;

CREATE TABLE IF NOT EXISTS `warehouseManagement`.`Items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Itemname` VARCHAR(200) NOT NULL,
  `Category_Id` INT NOT NULL,
  `Unit` VARCHAR(45) NULL,
  `Location` VARCHAR(200) NULL,
  `Description` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Itemname_UNIQUE` (`Itemname` ASC) VISIBLE,
  INDEX `Items_Category_idx` (`Category_Id` ASC) VISIBLE,
  CONSTRAINT `Items_Category`
    FOREIGN KEY (`Category_Id`)
    REFERENCES `warehouseManagement`.`Categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouseManagement`.`Settlement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouseManagement`.`Settlement` ;

CREATE TABLE IF NOT EXISTS `warehouseManagement`.`Settlement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Item_Id` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `Settle_Date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Settlement_Item_Id_idx` (`Item_Id` ASC) VISIBLE,
  CONSTRAINT `Settlement_Item_Id`
    FOREIGN KEY (`Item_Id`)
    REFERENCES `warehouseManagement`.`Items` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouseManagement`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouseManagement`.`Transactions` ;

CREATE TABLE IF NOT EXISTS `warehouseManagement`.`Transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Item_Id` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `Transaction_Date` DATE NOT NULL,
  `User_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`User_Id` ASC) VISIBLE,
  INDEX `item_id_idx` (`Item_Id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`User_Id`)
    REFERENCES `warehouseManagement`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_id`
    FOREIGN KEY (`Item_Id`)
    REFERENCES `warehouseManagement`.`Items` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
